### ISSUE TITLE
how do i include custom dictionary in petrarch(2)? 

### ISSUE THREAD

**Issue by cliffnyang** [openeventdata/petrarch2#19]
Hi guys, is it possible to include a customized event type dictionary into Petrarch(2)? I understand that Petrarch(2) is CAMEO based and I have some organic definitions derived from other sources. Any suggestions? Thanks!

**Comment by philip-schrodt** [comment]
Phrase dictionaries are located in the data/dictionaries. PETRARCH-2 is, as you noted, fairly tightly integrated into CAMEO in the sense that various verb combinations can generate new events, and certain types of events generate secondary events. Most of this is documented in the Petrarch2.pdf file, and the translation from those internal representations to CAMEO is in the convert_code() function in utilities.py -- it's pretty well documented. The various other transformations are scattered through PETRtree.py -- again, with pretty decent documentation -- and also there are about ten general transformations are the end of the file CAMEO.2.0.txt
