### ISSUE TITLE
Config file and parsing for NullVerbs and NullActors

### ISSUE THREAD

**Issue by ahalterman** [openeventdata/petrarch2#24]
The NullVerbs and NullActor options that @philip-schrodt added [here](https://github.com/openeventdata/petrarch2/pull/20/commits/4435671ce048032344f81c7c217c47d514e84904) are turned on and off in `PETRglobals`. Add an option to the [config file](https://github.com/openeventdata/petrarch2/blob/master/petrarch2/PETRglobals.py#L55-L56) and the config parser (similar to [here](https://github.com/openeventdata/petrarch2/blob/21e0fb967ec004981a6a266f4d116306a8e896d8/petrarch2/PETRreader.py#L172-L181)) to enable the config file to change these options.

**Comment by philip-schrodt** [comment]
Options have been added; internal comments and documentation in Petrarch2.tex were modified to reflect this.
