### ISSUE TITLE
Incorrect Command line Parsing Function: parse_cli_args

### ISSUE THREAD

**Issue by ruslanrf** [openeventdata/petrarch2#26]
`python2.7 petrarch2.py parse -i ./data/text/GigaWord.sample.PETR.xml -o my_output` leads to the following problem:

```
Traceback (most recent call last):
...
  File ".../petrarch2/petrarch2.py", line 530, in <module>
    main()
  File ".../petrarch2/petrarch2.py", line 438, in main
    if cli_args.outputs:
AttributeError: 'Namespace' object has no attribute 'outputs'
```

Furthermore, "-o" argument of the batch mode has an incorrect description.

**Comment by ruslanrf** [comment]
I will close the issue as the batch mode is recommended and the input (xml) file has to be parsed.

However, there are minor issues related to the "-o" argument of the batch mode and some variables and function calls (e.g. `utilities.stanford_parse(events)`) which aren't defined.

**Comment by johnb30** [comment]
Thanks for the issue. I've got a branch open to clean up some of the CLI args. The next major release will have things consolidated.
