### ISSUE TITLE
ImportError: No module named 'PETRglobals'

### ISSUE THREAD

**Issue by atuls-tatras** [openeventdata/petrarch2#47]
I installed patrarch2 in ubuntu 16.04 using pip3.5. but using petrarch2 -h gives me following error
ImportError: No module named 'PETRglobals'

Also I am not able to install PETRglobals using `pip install PETRglobals`

However, It works perfectly fine with pip2.7

**Comment by ahalterman** [comment]
Yes, unfortunately Petrarch2 only works with Python 2 and gives that completely opaque message when you try to use it with Python 3. I've updated the `README` to specify Python 2 and hopefully this error will help future people.
