### ISSUE TITLE
Code to extract Arabic actor and event phrases

### ISSUE THREAD

**Issue by ahalterman** [openeventdata/petrarch2#8]
Although we'll be switching to Universal Dependencies in the medium term (#7), we have an immediate need for the ability to extract actor and verb phrases from Arabic so that we can begin human coding (and machine-assisted) dictionary development. The phrases extracted should be suitable for adding to the dictionaries and dictionary entries alongside their human-assigned code, meaning that they should mirror the way that Petrarch2 will see the phrases.

This code will be somewhat parallel to the later UD approach, but hopefully writing it will help with the future integration of Arabic text into Petrarch2.

**Comment by johnb30** [comment]
Closing because multi-lingual is out-of-scope for this iteration of PETRARCH. Multi-lingual work is ongoing in https://github.com/openeventdata/UniversalPetrarch.
